language: python

cache: pip

python:
  - "3.8"

install:
  - pip install poetry
  - poetry install

before_deploy:
  - make docs

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local-dir: site
    on:
      branch: main
