name: Github pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create site directory
        run: |
          mkdir site || true
          cp src/avatar.jpeg site/avatar.jpeg

      - uses: docker://pandoc/latex:2.6
        with:
          args: src/profile.yml -o site/index.html --template=template/index.html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
